sudo: required

language: generic

services:
    - docker
    
before_install:
    - docker build -t tharoon/docker-reactCI -f Dockerfile.dev .

script:
        - docker run -e CI=true tharoon/docker-reactCI npm run test -- --coverage