language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t tharoon/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tharoon/docker-react npm run test
  
deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-tcubeReact"
    env: "DockerTcubereact-env"
    bucket_name: "elasticbeanstalk-us-east-2-928477002313"
    bucket_path: "docker-tcubeReact"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY   
  
  